export default function renderContentfulImports(
  localization: boolean = false,
  hasRichText: boolean = true,
): string {
  return `
    // THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

    ${localization ? "" : "import type { Asset } from 'contentful'"}
    import type { Content as Entry${
      hasRichText ? ", RichTextNode as Document" : ""
    }} from './bedrock'
  `
}
